version = "0.10.0"
deployment = "deployment.toml"

[rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
workspace_dir = "."

[[contracts]]
name = "bridge-lockscript"
template_type = "Rust"

[[contracts]]
name = "recipient-typescript"
template_type = "Rust"
